/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sistema/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Ping simple: devuelve versión del paquete y existencia de directorios.
         */
        get: operations["health_api_sistema_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presupuesto/_resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resumen
         * @description Panel de KPIs del bloque Presupuesto.
         */
        get: operations["resumen_api_presupuesto__resumen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presupuesto/uc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Uc
         * @description Listado paginado de unidades de coste de presupuesto.
         */
        get: operations["listar_uc_api_presupuesto_uc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presupuesto/uc/{uc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Uc
         * @description Ficha de una UC concreta, con enriquecimientos.
         */
        get: operations["obtener_uc_api_presupuesto_uc__uc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cargos/_resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumen */
        get: operations["resumen_api_cargos__resumen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cargos/categoria_pdi_pvi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Categoria */
        get: operations["listar_categoria_api_cargos_categoria_pdi_pvi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cargos/categoria_pdi_pvi/{per_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Categoria */
        get: operations["obtener_categoria_api_cargos_categoria_pdi_pvi__per_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cargos/departamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Departamentos */
        get: operations["listar_departamentos_api_cargos_departamentos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cargos/departamentos/{idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Cargo */
        get: operations["obtener_cargo_api_cargos_departamentos__idx__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/superficies/_resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumen */
        get: operations["resumen_api_superficies__resumen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/superficies/totales/complejos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Complejos */
        get: operations["listar_complejos_api_superficies_totales_complejos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/superficies/totales/edificaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Edificaciones */
        get: operations["listar_edificaciones_api_superficies_totales_edificaciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/superficies/totales/zonas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Zonas */
        get: operations["listar_zonas_api_superficies_totales_zonas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entradas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalogo
         * @description Listado de subdirectorios y ficheros de data/entrada/.
         */
        get: operations["catalogo_api_entradas__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entradas/xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Leer Xlsx
         * @description Devuelve un Excel paginado con filtro/sort comunes.
         */
        get: operations["leer_xlsx_api_entradas_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entradas/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Leer Tree
         * @description Devuelve un árbol .tree serializado como JSON jerárquico.
         */
        get: operations["leer_tree_api_entradas_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/_resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumen */
        get: operations["resumen_api_amortizaciones__resumen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/enriquecido": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enriquecido */
        get: operations["enriquecido_api_amortizaciones_enriquecido_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/filtrados/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filtrados Estado */
        get: operations["filtrados_estado_api_amortizaciones_filtrados_estado_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/filtrados/cuenta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filtrados Cuenta */
        get: operations["filtrados_cuenta_api_amortizaciones_filtrados_cuenta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/filtrados/fecha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filtrados Fecha */
        get: operations["filtrados_fecha_api_amortizaciones_filtrados_fecha_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/sin-cuenta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sin Cuenta */
        get: operations["sin_cuenta_api_amortizaciones_sin_cuenta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/sin-fecha-alta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sin Fecha Alta */
        get: operations["sin_fecha_alta_api_amortizaciones_sin_fecha_alta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/detalle-cuentas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle Cuentas */
        get: operations["detalle_cuentas_api_amortizaciones_detalle_cuentas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/sin-uc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sin Uc */
        get: operations["sin_uc_api_amortizaciones_sin_uc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/uc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Uc */
        get: operations["uc_api_amortizaciones_uc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/enriquecido/{reg_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Enriquecido */
        get: operations["obtener_enriquecido_api_amortizaciones_enriquecido__reg_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amortizaciones/uc/{uc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Uc */
        get: operations["obtener_uc_api_amortizaciones_uc__uc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/_resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumen */
        get: operations["resumen_api_personal__resumen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/expedientes/{sector}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Sector */
        get: operations["listar_sector_api_personal_expedientes__sector__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/expedientes/{sector}/{expediente}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Expediente */
        get: operations["obtener_expediente_api_personal_expedientes__sector___expediente__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/multiexpediente": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Multiexpediente */
        get: operations["multiexpediente_api_personal_multiexpediente_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/persona": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Personas */
        get: operations["listar_personas_api_personal_persona_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/persona/{per_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Persona */
        get: operations["obtener_persona_api_personal_persona__per_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/persona/{per_id}/uc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Uc Persona */
        get: operations["listar_uc_persona_api_personal_persona__per_id__uc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/anomalias-pdi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anomalias Pdi */
        get: operations["anomalias_pdi_api_personal_anomalias_pdi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CatalogoEntradas */
        CatalogoEntradas: {
            /** Grupos */
            grupos: components["schemas"]["GrupoEntradas"][];
        };
        /**
         * ColumnSpec
         * @description Descripción de una columna de una tabla servida al frontend.
         */
        ColumnSpec: {
            /**
             * Name
             * @description Nombre interno de la columna
             */
            name: string;
            /**
             * Label
             * @description Etiqueta humana mostrada en cabecera
             */
            label: string;
            /**
             * Format
             * @default text
             * @enum {string}
             */
            format: "text" | "int" | "float" | "euro" | "m2" | "date" | "bool";
            /**
             * Sortable
             * @default true
             */
            sortable: boolean;
        };
        /** FicheroEntrada */
        FicheroEntrada: {
            /** Nombre */
            nombre: string;
            /** Stem */
            stem: string;
            /** Extension */
            extension: string;
            /** Ruta Relativa */
            ruta_relativa: string;
            /** Tamaño Bytes */
            "tama\u00F1o_bytes": number;
        };
        /**
         * FieldValue
         * @description Un par (campo, valor) ya formateado para la ficha de registro.
         */
        FieldValue: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Value */
            value: unknown;
            /**
             * Format
             * @default text
             * @enum {string}
             */
            format: "text" | "int" | "float" | "euro" | "m2" | "date" | "bool";
        };
        /** GrupoEntradas */
        GrupoEntradas: {
            /** Subdirectorio */
            subdirectorio: string;
            /** Ficheros */
            ficheros: components["schemas"]["FicheroEntrada"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Entrada Existe */
            entrada_existe: boolean;
            /** Fase1 Existe */
            fase1_existe: boolean;
        };
        /**
         * Kpi
         * @description Métrica agregada que se muestra en el panel KPI de cabecera.
         */
        Kpi: {
            /** Label */
            label: string;
            /** Value */
            value: number | string | null;
            /**
             * Format
             * @default text
             * @enum {string}
             */
            format: "text" | "int" | "float" | "euro" | "m2" | "date" | "bool";
            /** Hint */
            hint?: string | null;
        };
        /** KpiPanel */
        KpiPanel: {
            /** Kpis */
            kpis: components["schemas"]["Kpi"][];
        };
        /**
         * ListResponse
         * @description Respuesta común para listados con filtro/sort/paginación.
         *
         *     El frontend usa ``columns`` para conocer formato y orden visual de las
         *     columnas; ``rows`` es una lista de diccionarios con valores ya
         *     serializables a JSON; ``total`` es el número total de filas tras aplicar
         *     el filtro pero antes de paginar.
         */
        ListResponse: {
            /** Columns */
            columns: components["schemas"]["ColumnSpec"][];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Total */
            total: number;
        };
        /** NodoTree */
        NodoTree: {
            /** Código */
            "c\u00F3digo": string;
            /** Descripción */
            "descripci\u00F3n": string;
            /** Identificador */
            identificador: string;
            /**
             * Hijos
             * @default []
             */
            hijos: components["schemas"]["NodoTree"][];
        };
        /**
         * RecordResponse
         * @description Ficha completa de un registro: campos directos + secciones enriquecidas.
         *
         *     El primer bloque (``main``) son los campos del propio registro; los
         *     enriquecimientos (lookup de personas, titulaciones, etc.) van en
         *     ``sections``.
         */
        RecordResponse: {
            /** Main */
            main: components["schemas"]["FieldValue"][];
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["RecordSection"][];
        };
        /**
         * RecordSection
         * @description Una sección de la ficha (puede haber varias para enriquecimientos).
         */
        RecordSection: {
            /** Label */
            label: string;
            /** Fields */
            fields: components["schemas"]["FieldValue"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_sistema_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    resumen_api_presupuesto__resumen_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiPanel"];
                };
            };
        };
    };
    listar_uc_api_presupuesto_uc_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_uc_api_presupuesto_uc__uc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumen_api_cargos__resumen_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiPanel"];
                };
            };
        };
    };
    listar_categoria_api_cargos_categoria_pdi_pvi_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_categoria_api_cargos_categoria_pdi_pvi__per_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                per_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_departamentos_api_cargos_departamentos_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_cargo_api_cargos_departamentos__idx__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumen_api_superficies__resumen_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiPanel"];
                };
            };
        };
    };
    listar_complejos_api_superficies_totales_complejos_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_edificaciones_api_superficies_totales_edificaciones_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_zonas_api_superficies_totales_zonas_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogo_api_entradas__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogoEntradas"];
                };
            };
        };
    };
    leer_xlsx_api_entradas_xlsx_get: {
        parameters: {
            query: {
                /** @description Ruta relativa a data/entrada/ */
                ruta: string;
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leer_tree_api_entradas_tree_get: {
        parameters: {
            query: {
                /** @description Ruta relativa a data/entrada/ */
                ruta: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodoTree"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumen_api_amortizaciones__resumen_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiPanel"];
                };
            };
        };
    };
    enriquecido_api_amortizaciones_enriquecido_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filtrados_estado_api_amortizaciones_filtrados_estado_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filtrados_cuenta_api_amortizaciones_filtrados_cuenta_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filtrados_fecha_api_amortizaciones_filtrados_fecha_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sin_cuenta_api_amortizaciones_sin_cuenta_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sin_fecha_alta_api_amortizaciones_sin_fecha_alta_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detalle_cuentas_api_amortizaciones_detalle_cuentas_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sin_uc_api_amortizaciones_sin_uc_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uc_api_amortizaciones_uc_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_enriquecido_api_amortizaciones_enriquecido__reg_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reg_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_uc_api_amortizaciones_uc__uc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumen_api_personal__resumen_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiPanel"];
                };
            };
        };
    };
    listar_sector_api_personal_expedientes__sector__get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                sector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_expediente_api_personal_expedientes__sector___expediente__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector: string;
                expediente: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    multiexpediente_api_personal_multiexpediente_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_personas_api_personal_persona_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_persona_api_personal_persona__per_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                per_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_uc_persona_api_personal_persona__per_id__uc_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                per_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anomalias_pdi_api_personal_anomalias_pdi_get: {
        parameters: {
            query?: {
                /** @description Substring a buscar (insensible a tildes y mayúsculas) */
                q?: string | null;
                /** @description Columna sobre la que aplicar `q` (None = todas las columnas string) */
                column?: string | null;
                /** @description Columna por la que ordenar */
                sort_by?: string | null;
                /** @description Orden descendente */
                desc?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
